<?php

/**
 * Generated By Subapp\Orm Generator
 * @author Ivan Hontarenko
 */

/**
 * IMPORTANT:
 *      Don't edit this file!
 *      This file was generated automatically, and it can happen again
 *      and as a consequence it will overwrite your changes.
 */

namespace IdPorn\Dbl\Base;

use Subapp\Orm\Core\Entity;

/**
 * Entity class for representation table 'stars'
 */
class BaseStar extends Entity
{

    const TABLE = 'stars';

    const ID = 'stars.id';
    const NAME = 'stars.name';
    const CREATED_AT = 'stars.created_at';
    const ID_KEY = 'id';
    const NAME_KEY = 'name';
    const CREATED_AT_KEY = 'created_at';

    /**
    * @var integer
    */
    public $id;

    /**
    * @var string
    */
    public $name;

    /**
    * @var string
    */
    public $createdAt;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }


    /**
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @param string $createdAt
     * @return $this
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

}