<?php

/**
 * Generated By Subapp\Orm Generator
 * @author Ivan Hontarenko
 *
 * IMPORTANT:
 *      Don't edit this file!
 *      This file was generated automatically, and it can happen again
 *      and as a consequence it will overwrite your changes.
 */

namespace CvLand\PhpDatabaseLayer\Base;

use Subapp\Orm\Core\Entity;

/**
 * Entity class for representation table 'systemUser'
 */
class BaseSystemUser extends Entity
{

    const TABLE = 'systemUser';

    const ID = 'systemUser.id';
    const NAME = 'systemUser.name';
    const PASSWORD = 'systemUser.password';
    const ACCESS = 'systemUser.accessBitMask';
    const CREATED = 'systemUser.created';
    const ID_KEY = 'id';
    const NAME_KEY = 'name';
    const PASSWORD_KEY = 'password';
    const ACCESS_KEY = 'accessBitMask';
    const CREATED_KEY = 'created';

    /**
    * @var integer
    */
    public $id;

    /**
    * @var string
    */
    public $name;

    /**
    * @var string
    */
    public $password;

    /**
    * @var integer
    */
    public $access;

    /**
    * @var string
    */
    public $created;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @return integer
     */
    public function getAccess()
    {
        return $this->access;
    }

    /**
     * @return string
     */
    public function getCreated()
    {
        return $this->created;
    }


    /**
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @param string $password
     * @return $this
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @param integer $access
     * @return $this
     */
    public function setAccess($access)
    {
        $this->access = $access;

        return $this;
    }

    /**
     * @param string $created
     * @return $this
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

}