<?php

/**
 * Generated By Subapp\Orm Generator
 * @author Ivan Hontarenko
 *
 * IMPORTANT:
 *      Don't edit this file!
 *      This file was generated automatically, and it can happen again
 *      and as a consequence it will overwrite your changes.
 */

namespace CvLand\PhpDatabaseLayer\Base;

use Subapp\Orm\Core\Entity;

/**
 * Entity class for representation table 'systemUserToken'
 */
class BaseSystemUserToken extends Entity
{

    const TABLE = 'systemUserToken';

    const ID = 'systemUserToken.id';
    const USER_ID = 'systemUserToken.userId';
    const TOKEN = 'systemUserToken.token';
    const CREATED = 'systemUserToken.created';
    const ID_KEY = 'id';
    const USER_ID_KEY = 'userId';
    const TOKEN_KEY = 'token';
    const CREATED_KEY = 'created';

    /**
    * @var integer
    */
    public $id;

    /**
    * @var integer
    */
    public $userId;

    /**
    * @var string
    */
    public $token;

    /**
    * @var string
    */
    public $created;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return integer
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * @return string
     */
    public function getCreated()
    {
        return $this->created;
    }


    /**
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @param integer $userId
     * @return $this
     */
    public function setUserId($userId)
    {
        $this->userId = $userId;

        return $this;
    }

    /**
     * @param string $token
     * @return $this
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * @param string $created
     * @return $this
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

}