<?php

/**
 * Generated By Subapp\Orm Generator
 * @author Ivan Hontarenko
 */

$classLoader = new Composer\Autoload\ClassLoader();
$classLoader->setPsr4('IdPorn\Dbl\\', __DIR__);
$classLoader->register(true);

return $classLoader;