<?php

/**
 * Generated By Subapp\Orm Generator
 * @author Ivan Hontarenko
 *
 * IMPORTANT:
 *      Don't edit this file!
 *      This file was generated automatically, and it can happen again
 *      and as a consequence it will overwrite your changes.
 */

$classLoader = new Composer\Autoload\ClassLoader();
$classLoader->setPsr4('CvLand\PhpDatabaseLayer\\', __DIR__);
$classLoader->register(true);

return $classLoader;